development:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: 'michal.narajowski@gmail.com'
  :password: 'C845P-MqFH7bMMrXaZkjnQ'
  :enable_starttls_auto: true
production:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: 'michal.narajowski@gmail.com'
  :password: 'C845P-MqFH7bMMrXaZkjnQ'
  :enable_starttls_auto: true