# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e98360a81e6e649659b05c2d7c274e9b3b58fc481184c58ea919946a4e47fc9b90b90f04d6d79b94f0d9388141c1064c38ca1bc924377a7374afc1b249591698

test:
  secret_key_base: 435ea11362b24e1c10a3bde9a16aa94a565b372202ca10eae4f05d585abdbf47f4d82197f7ee9e61375512b399c8cca74c696df22b3458e301cef8a85b8a8e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
